version: '3'

services:
  # bot-api:
  #   build:
  #     context: ./
  #     dockerfile: api/Dockerfile
  #   ports:
  #     - "8080:8080"

  # bot-bot:
  #   build: 
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   volumes:
  #     - type: bind
  #       source: ./bot
  #       target: /app
  
  bot-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "3000:3000"

  bot-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=bot
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  db:
    driver: local
      


  # networks:
  #   frontend:
  #     name: custom_frontend
  #     driver: custom-driver-1